import { Schema } from "effect";
import { addDays, weekStart, RecipeSchema, MealSchema } from "./domain";

export const sampleRecipes = Schema.decodeUnknownSync(Schema.Array(RecipeSchema))([
  {
    id: "lemon-chicken",
    title: "Lemon & herb chicken",
    description: "Golden, crisp-skinned chicken with lemon, garlic, and a generous handful of garden herbs.",
    servings: 4,
    minutes: 45,
    category: "Weeknight favorites",
    photo: "/photos/chicken.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/roast-chicken-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Chicken thighs", quantity: 800, unit: "g" },
      { name: "Lemon", quantity: 2, unit: "each" },
      { name: "Garlic", quantity: 4, unit: "clove" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Rosemary", quantity: 1, unit: "bunch" },
    ],
    instructions: [
      "Heat the oven to 220°C / 425°F. Pat the chicken thighs dry and place in a roasting dish.",
      "Combine olive oil, crushed garlic, chopped rosemary, and the zest and juice of one lemon. Rub over the chicken and season to taste.",
      "Slice the remaining lemon and tuck around the chicken. Roast for 35–40 minutes, until the thickest part reaches 74°C / 165°F.",
      "Rest for 5 minutes. Spoon over the pan juices and serve with your favorite greens.",
    ],
  },
  {
    id: "tomato-pasta",
    title: "Roasted tomato pasta",
    description: "Slow-roasted tomatoes, fresh basil, and a little parmesan. Simple things, done well.",
    servings: 4,
    minutes: 35,
    category: "Vegetarian",
    photo: "/photos/pasta.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/tomato-pasta-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Pasta", quantity: 400, unit: "g" },
      { name: "Cherry tomatoes", quantity: 600, unit: "g" },
      { name: "Garlic", quantity: 3, unit: "clove" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Basil", quantity: 1, unit: "bunch" },
      { name: "Parmesan", quantity: 60, unit: "g" },
    ],
    instructions: [
      "Heat the oven to 200°C / 400°F. Toss tomatoes and sliced garlic with olive oil in a roasting dish.",
      "Roast for 25 minutes until softened and lightly caramelized.",
      "Cook pasta in salted water until al dente. Reserve a cup of cooking water, then drain.",
      "Toss pasta with the tomatoes, torn basil, and parmesan. Add a splash of cooking water to bring the sauce together.",
    ],
  },
  {
    id: "grain-bowl",
    title: "Green goddess grain bowl",
    description: "A colorful bowl of fluffy quinoa, crunchy greens, chickpeas, and a bright lemon dressing.",
    servings: 2,
    minutes: 25,
    category: "Vegetarian",
    photo: "/photos/bowl.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/grain-bowl-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Quinoa", quantity: 150, unit: "g" },
      { name: "Chickpeas", quantity: 1, unit: "can" },
      { name: "Avocado", quantity: 1, unit: "each" },
      { name: "Spinach", quantity: 100, unit: "g" },
      { name: "Lemon", quantity: 1, unit: "each" },
      { name: "Olive oil", quantity: 1, unit: "tbsp" },
    ],
    instructions: [
      "Rinse quinoa and simmer in 300 ml water for 15 minutes. Leave covered for 5 minutes, then fluff.",
      "Drain and rinse the chickpeas. Slice the avocado and wash the spinach.",
      "Whisk the lemon juice with olive oil and season to taste.",
      "Divide quinoa between bowls. Arrange chickpeas, avocado, and spinach on top, then drizzle with the dressing.",
    ],
  },
  {
    id: "salmon",
    title: "Honey garlic salmon",
    description: "Sticky, savory salmon with a caramelized edge. A weeknight dinner worth slowing down for.",
    servings: 4,
    minutes: 25,
    category: "Weeknight favorites",
    photo: "/photos/salmon.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/salmon-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Salmon", quantity: 600, unit: "g" },
      { name: "Honey", quantity: 2, unit: "tbsp" },
      { name: "Soy sauce", quantity: 2, unit: "tbsp" },
      { name: "Garlic", quantity: 3, unit: "clove" },
      { name: "Rice", quantity: 300, unit: "g" },
      { name: "Broccoli", quantity: 400, unit: "g" },
    ],
    instructions: [
      "Cook the rice according to its packet instructions. Cut broccoli into florets and steam until tender.",
      "Mix honey, soy sauce, and crushed garlic.",
      "Place salmon in a baking dish, spoon over the glaze, and bake at 200°C / 400°F for 12–15 minutes, until the center reaches 63°C / 145°F.",
      "Serve over rice with broccoli and the remaining cooked glaze.",
    ],
  },
  {
    id: "soup",
    title: "Creamy roasted tomato soup",
    description: "A cozy bowl of roasted tomatoes and basil, made for a thick slice of toasted bread.",
    servings: 4,
    minutes: 40,
    category: "Comfort food",
    photo: "/photos/soup.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/tomato-soup-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Cherry tomatoes", quantity: 800, unit: "g" },
      { name: "Onion", quantity: 1, unit: "each" },
      { name: "Garlic", quantity: 4, unit: "clove" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Vegetable stock", quantity: 500, unit: "ml" },
      { name: "Cream", quantity: 100, unit: "ml" },
      { name: "Basil", quantity: 1, unit: "bunch" },
    ],
    instructions: [
      "Heat the oven to 220°C / 425°F. Halve the tomatoes and roughly chop the onion.",
      "Toss tomatoes, onion, and garlic with olive oil. Roast for 25 minutes.",
      "Transfer to a saucepan with vegetable stock. Simmer for 10 minutes, then blend until smooth.",
      "Stir in cream and torn basil. Season to taste and serve warm.",
    ],
  },
  {
    id: "tacos",
    title: "Smoky sweet potato tacos",
    description: "Roasted sweet potato, black beans, and creamy avocado tucked into warm tortillas.",
    servings: 4,
    minutes: 35,
    category: "Vegetarian",
    photo: "/photos/tacos.jpg",
    source: "https://www.bbcgoodfood.com/recipes/collection/vegetarian-taco-recipes",
    rating: "neutral",
    ingredients: [
      { name: "Sweet potato", quantity: 600, unit: "g" },
      { name: "Black beans", quantity: 1, unit: "can" },
      { name: "Tortillas", quantity: 8, unit: "each" },
      { name: "Avocado", quantity: 1, unit: "each" },
      { name: "Lime", quantity: 2, unit: "each" },
      { name: "Olive oil", quantity: 1, unit: "tbsp" },
      { name: "Smoked paprika", quantity: 2, unit: "tsp" },
    ],
    instructions: [
      "Dice sweet potatoes and toss with olive oil and smoked paprika. Roast at 220°C / 425°F for 25 minutes.",
      "Drain black beans and warm in a saucepan with a splash of water.",
      "Mash avocado with the juice of one lime. Warm tortillas in a dry pan.",
      "Fill tortillas with potatoes, beans, and avocado. Serve with lime wedges.",
    ],
  },
]);

export function sampleMeals(today: string) {
  const monday = weekStart(today);

  return Schema.decodeUnknownSync(Schema.Array(MealSchema))([
    {
      id: "sample-1",
      recipeId: "lemon-chicken",
      date: monday,
      slot: "Dinner",
      scale: 1,
      note: "With a big green salad",
    },
    {
      id: "sample-2",
      recipeId: "tomato-pasta",
      date: addDays(monday, 1),
      slot: "Dinner",
      scale: 1.5,
      note: "Extra for tomorrow’s lunch",
    },
    {
      id: "sample-3",
      recipeId: "grain-bowl",
      date: addDays(monday, 2),
      slot: "Lunch",
      scale: 2,
      note: "Add chicken to Alex’s bowl",
    },
    { id: "sample-4", recipeId: "salmon", date: addDays(monday, 3), slot: "Dinner", scale: 1, note: "" },
    {
      id: "sample-5",
      recipeId: "tacos",
      date: addDays(monday, 5),
      slot: "Dinner",
      scale: 1,
      note: "Taco night!",
    },
  ]);
}
